{% set name = "robocorp-log" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp_log-{{ version }}.tar.gz
  sha256: f3dc7e31bdbb57ceb54d9e2c89e9ec30d67f9c7c46e6e6c0e16be5eb5b32c341

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - tomli <3.0.0,>=2.0.1
    - psutil >=5.0,<8.0

test:
  imports:
    - robocorp.log
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robo/
  summary: Automatic trace logging for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
