{% set name = "robocorp-log" %}
{% set version = "2.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp_log-{{ version }}.tar.gz
  sha256: 67f88dba5ce626b42e645e7dfe60abd78edd50d17a1a2f6c554c78c1d2ca1176

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - tomli <3.0.0,>=2.0.1
    - psutil <6.0,>=5.9

test:
  imports:
    - robocorp.log
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robo/
  summary: Automatic trace logging for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
